export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  PRESIDENT = 'ROLE_PRESIDENT',
  VICE_PRESIDENT = 'ROLE_VICE_PRESIDENT',
  DIRECTOR = 'ROLE_DIRECTOR',
  MANAGER = 'ROLE_MANAGER',
  TEAM_LEADER = 'ROLE_TEAM_LEADER',
  AUDITOR = 'ROLE_AUDITOR',
  OTHER = 'ROLE_OTHER',
  ANONYMOUS = 'ROLE_ANONYMOUS'
}
