export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ROLE_PRESIDENT = 'ROLE_PRESIDENT',
  ROLE_VICE_PRESIDENT = 'ROLE_VICE_PRESIDENT',
  ROLE_DIRECTOR = 'ROLE_DIRECTOR',
  ROLE_MANAGER = 'ROLE_MANAGER',
  ROLE_TEAM_LEADER = 'ROLE_TEAM_LEADER',
  ROLE_AUDITOR = 'ROLE_AUDITOR',
  ROLE_OTHER = 'ROLE_OTHER',
  ROLE_ANONYMOUS = 'ROLE_ANONYMOUS'
}
